### ISSUE TITLE
trimming and passing check

### ISSUE THREAD

**Issue by vjcitn** [HelenaLC/SpatialData#55]
I have forked the package and will remove the merfish.zarr from extdata.  I will issue a PR
once I have introduced a function that retrieves the necessary data from Bioc Open Storage
Network and caches it in BiocFileCache.

I will not PR until the package is passing check, but I hope that can happen soon.

**Comment by vjcitn** [comment]
I would propose that we avoid including all but the smallest demonstration data elements to
our packages.  The [alabaster](https://www.bioconductor.org/packages/release/bioc/vignettes/alabaster.base/inst/doc/userguide.html)/[gypsum](https://bioconductor.org/packages/release/bioc/vignettes/gypsum/inst/doc/userguide.html) APIs should be looked at for achieving language-agnostic
data repositories, but we are not at a point where it is clear how to adopt them.

**Comment by HelenaLC** [comment]
Agreed. The idea is to instead include examples from [here](https://github.com/scverse/spatialdata-notebooks/tree/main/notebooks/developers_resources/storage_format), however, I am awaiting these to be updated. Alternatively, once we have something functional, we could mock up & write out minimal example data, because it still would be nice to include a www-independent example, I think.

**Comment by vjcitn** [comment]
I have a bucket already set up.  We can use it until we decide on a canonical longer-term solution.
