### ISSUE TITLE
guessing multiscale is counter intuitive?

### ISSUE THREAD

**Issue by HelenaLC** [HelenaLC/SpatialData#84]
- `.guess_scale` currently "rounds up to the next scale"
- e.g., `width=height=11` for scales 20x20 and 10x10 would choose 20x20
- my intuition would be to instead minimize the total difference in input/output size
- e.g., `w=h=11` would choose 10x10, `w=h=16` 20x20, and `w=h=15` is for us to decide

Thumbs up if you agree @Artur-man, else happy to discuss/learn about the reasoning behind the current implementation!

**Comment by Artur-man** [comment]
ah very good point ... when I have discussed this with @melonora and @LucaMarconato, they mentioned to me that you first pick the scale that is closest to the target resolution, from there, you rasterize and decrease the resolution to fit the targeted resolution. 

Here is a good example: 

This is the multiscale image of VisiumHD example
(3, 21943, 23618), (3, 10971, 11809), (3, 5485, 5904), (3, 2742, 2952), (3, 1371, 1476)

Say that you wanna visualize the image with ... (2500, 2600) resolution. The closest resolution in the list of scales is (2742, 2952) then, if needed, you downgrade the resolution from (2742, 2952) to (2500, 2600), I thought it is better the change the resolution from a higher resolution rather than a lower resolution, meaning when you transform the (1371, 1476) image to (2500, 2600) you lose more information. 

However, I am happy with which strategy you wanna go, at the end of the day the idea is to get a lower resolution image in the memory :D

**Comment by melonora** [comment]
Hello there! Please see https://github.com/scverse/spatialdata-plot/blob/0667ef8bf0633ad9574bbf4dd6e5defd60a6762f/src/spatialdata_plot/pl/utils.py#L1282C6-L1352 for the implementation in `spatialdata-plot`. This takes the figure width, height and dpi into account.

**Comment by melonora** [comment]
Thinking back I think for choosing the higher scale was mainly due to the fact that you would have to choose an interpolation so that would be another parameter.

**Comment by HelenaLC** [comment]
@Artur-man - regarding the example you gave for Visium HD with 1=(3, 21943, 23618), 2=(3, 10971, 11809), 3=(3, 5485, 5904), 4=(3, 2742, 2952), 5=(3, 1371, 1476), input (2500, 2600) should still pick 4. 

However, for (3, 2700, 3000), we would now realize 3 into memory, which is not what I'd expect. Intuitively, we want to 
1. minimize what is realized into memory
2. minimize the blur visible to the user

So I would instead suggest something like...
```
> x <- file.path("extdata", "blobs.zarr")
> x <- system.file(x, package="SpatialData")
> x <- readSpatialData(x, tables=FALSE)
> x <- image(x, "blobs_multiscale_image")
> 
> # get array extends
> (d <- vapply(x@data, dim, numeric(3)))
     [,1] [,2] [,3]
[1,]    3    3    3
[2,]   64   32   16
[3,]   64   32   16
> 
> # set target width/height
> w <- 31; h <- 33
> 
> # get difference to target size
> (d <- apply(d, 2, \(.) sum(abs(.[-1]-c(h, w)))))
[1] 64  2 32
> 
> # choose 'which.min(d)' -> here, 2nd
> which.min(d)
[1] 2
```

**Comment by Artur-man** [comment]
I see ... I think I agree with this then, perhaps rasterization of images (after guessing image scale) is something we can discuss later!

**Comment by HelenaLC** [comment]
Yeah, I think that's a separate thing. I'll fix .guess_scale() for now - this is only for plotting, and one can always manually set the desired res., so should be fine. Also gonna give the option to pass Inf for "lowest available" so one doesn't have to know how many there are.
